### ISSUE TITLE
[Feature]: v3  k8s controller for creating a AI ability

### ISSUE THREAD

**Issue by whybeyoung** [iflytek/aiges#62]
### Tell us what feature you want?

Define a yaml like this: 

```yaml

apiVersion: v1
kind: AIService
metadata:
  name: yolov5-demo-service
spec:
  containerSpec: ...
  modelSpec: ...
```

After defined that , we can apply this to create an API using kubectl command native.
